# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

alias clean='gradle cleanEclipse && gradle eclipse'

color_option="%C(cyan)%h%C(reset) - %C(green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(yellow)%d%C(reset)"
alias log="git log --graph --abbrev-commit --decorate --format=format:'$color_option' --all"

alias init="rm -rf ./1d2f-portfoli/ && git clone https://github.com/yh0921k/1d2f-portfoli.git && cd ./1d2f-portfoli && clean"
